nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin:
            [
                "http://localhost:5173",
                "http://localhost:5174",
                "http://localhost:3000",
                "http://127.0.0.1:5173",
                "http://127.0.0.1:5174",
            ]
        allow_credentials: true
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allow_headers:
            ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/api/":
            origin_regex: false
            allow_origin:
                [
                    "http://localhost:5173",
                    "http://localhost:5174",
                    "http://localhost:3000",
                    "http://127.0.0.1:5173",
                    "http://127.0.0.1:5174",
                ]
            allow_credentials: true
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            allow_headers:
                ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
            max_age: 3600
        "^/login":
            origin_regex: false
            allow_origin:
                [
                    "http://localhost:5173",
                    "http://localhost:5174",
                    "http://localhost:3000",
                    "http://127.0.0.1:5173",
                    "http://127.0.0.1:5174",
                ]
            allow_credentials: true
            allow_methods: ["GET", "POST", "OPTIONS"]
            allow_headers:
                ["Content-Type", "Authorization", "Accept", "X-Requested-With"]
            max_age: 3600
        "^/payer":
            allow_origin: ["http://localhost:5173", "http://localhost:5174"]
            allow_methods: ["POST", "OPTIONS"]
            allow_headers: ["Content-Type", "Authorization"]
            max_age: 3600
